---
title: "Sum the data"
output: html_notebook
---

# Setup
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/egepehlivanoglu/Library/CloudStorage/OneDrive-StockholmUniversity/KVA backup/KVAOneDrive_backup_28Jan2026/2. Projects/4.Cascades/Editorial Review 20250807/map/Anthropocene-maps")

```

# 1. Deforestation

```{r Deforestation}
here::here("1.Deforestation/")
# only run the code
source("1.Deforestation/1.3.Deforestation_bin.R")

deforestation_bin_new <- deforestation_bin %>% select(x, y, binary_codes) %>% rename(value = binary_codes) # select only x, y, binary_codes columns and rename binary_codes to value for consistency with conflict dataset
```

# 2. Conflict

```{r Conflict}
# source the file for conflict (after threshold)
source(file = "2.Conflict/2.4.Conflict_after_threshold.R")
rm(list = ls()[!ls() %in% c("deforestation_bin", "world_moll_deforestation", "conflict_bin", "conflict_land_sf")]) # keep only these two datasets for the next steps, remove everything else to save memorysteps
conflict_bin_new <- conflict_bin %>% select(x, y, q50_bin) %>% rename(value = q50_bin) # select only x, y, q50_bin columns and rename q50_bin to value for consistency with deforestation dataset
```

# Sum 1 and 2

```{r}

# sum the two datasets (deforestation and conflict)
# make sure they have the same extent and resolution
# if not, resample one to match the other (e.g., using terra::res
# here we assume conflict_bin is the one to resample to match deforestation_bin
new_df <- terra::resample(conflict_bin, deforestation_bin, method= "near") # use nearest neighbor for categorical data
# now sum 
deforestation_bin_new$value <- as.numeric(as.character(deforestation_bin_new$value))
conflict_bin_new$value      <- as.numeric(as.character(conflict_bin_new$value))
# 
# combined <- deforestation_bin_new %>%
#   left_join(conflict_bin_new, by = c("x", "y"),
#             suffix = c("_def", "_conf")) %>%
#   mutate(
#     value_conf = ifelse(is.na(value_conf), 0, value_conf),
#     sum_value  = value_def + value_conf
  
```

# 4. Climate Change
```{r Climate Change}
# source the file for Climate change (after threshold areas with anomaly bigger than 2 degrees)
source(file = "4.Climate_change/4.3.Climate_change_after_cutoff.R")
```

# 5. Pesticide
```{r Pesticide}

# source the file for conflict (after threshold)
# double check with Peter if he confirms the threshold
source(file = "5.Pesticide_use/Tang 2021/5.2.Binary_RiskScores.R")
```

